spring:
  application:
    name: specialization-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1434;databaseName=specialization_db;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:yourStrong(!)Password}

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 10

secrets:
  jwt_secret: secret

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

application:
  application-service:
    url: ${APPLICATION_SERVICE_URL:http://localhost:8070}
