app:

spring:
  application:
    name: application-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=application_db;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:yourStrong(!)Password}

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS:http://localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.andrewsalygin.applicationservice.util.SpecializationOrDoctorSpecializationDeserializer
    properties:
      spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 10

secrets:
  jwt_secret: secret

server:
  port: 8070

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

application:
  specialization-service:
    url: ${SPECIALIZATION_SERVICE_URL:http://localhost:8090}
  kafka: true
