app:

spring:
  application:
    name: hospital

  datasource:
    url: jdbc:${DATASOURCE}://${DATASOURCE_IP_ADDRESS}:${DATASOURCE_PORT};database=${DATABASE};encrypt=true;trustServerCertificate=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

secrets:
  jwt_secret: ${JWT_SECRET}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
